### PR TITLE
Add bool function

### PR DESCRIPTION
**Pull request by etiennebatise**
Hi,

I've find your repository looking for the neat `bool` function available in [Haskell standard library](http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Bool.html#v:bool).

I had to rename occurrences of the word `bool` to `pred` for predicate to avoid shadowing errors. If you have a better naming alternative, let me know about it.

Regards,

### CODE REVIEW

**Comment by Chadtech** [comment]
Hey Etienne,

Thanks for the PR, but right now, this function doesnt look very useful in my opinion. What would someone use this for?

**Comment by cs** [comment]
I'm voting for this function. This is useful to safe a few lines on simple `if` statements. The Haskell version is definitely useful.

Example:

```elm
import Css as C

-- isActive : Bool
-- someColor : C.Color

-- Without bool function (after elm-format):
C.batch <|
    if isActive then
        [C.backgroundColor someColor]

    else
        []

-- With proposed bool function:
C.batch <| bool [] [ C.backgroundColor HC.superLightGray ] isActive
```

Saved 5 lines of code :) This should really be in the standard library in my opinion.

**Comment by Chadtech** [comment]
Hey Christoph! Nice seeing you.

I find reducing lines of code to be a pretty low priority thing. If thats all this is about, then I would think we shouldnt include it in `Bool-Extra`.

But I guess theres no other way to do an if statement inline within a pipe right? This would suck:
```elm
    |> (\bool -> if bool then [] else [ C.backgroundColor blue ])
```
Without this `bool` function, we all have to break out into a helper function, or write a lambda if you want to do an if statement in line with some other logic. 

If we do want to include this, can we use a better name than `bool`, and maybe swap the `a`s? Maybe..
```elm
ifElse : a -> a -> Bool -> a

    ifElse 1 2 True == 1
```

Just for some context, an earlier version of Bool-Extra had `ternary : a -> a -> Bool -> a`, where the first `a` would be returned if the `Bool` was `True`. This was modelled after `bool ? valueIfTrue : valueIfValue` in JavaScript, which has the opposite `a` order than Haskell's `bool` function. I took it out just because I didnt think there was enough value in it.

**Comment by cs** [comment]
Hey Chad!

I see two advantages with this function:

1. It helps to make code a bit denser, by reducing the number of lines of code (only true if using `elm-format`). This in turn makes it easier to read (fewer lines to scan).

2. It enables writing more point-free functions. Point-free is good, because (a) it also means denser code and much more importantly (b) less naming of stuff.

Another contrived example:
```elm
-- Without bool function:
f : Bool -> String
f whatever =
  if whatever then -- oh god, i have to find a meaningful name for the argument
    "i'm true"
  else
    "i'm false"

-- With bool function:
f : Bool -> String
f =
  bool "i'm false" "i'm true" 
```

I can't explain why they reversed the order of the arguments in the Haskell version. Understanding why they did that would be interesting, though. I'm sure they had a reason.

**Comment by cs** [comment]
As an aside: Something like `bool ? valueIfTrue : valueIfValue` is unlikely to ever happen in Elm, because **all** existing operators are binary and `?:` would be ternary. The same is true in Haskell.

**Comment by etiennebatise** [comment]
Hi  @Chadtech @cs ,

Sorry for not replying earlier. I agree with most of what you both said. The main purpose with this function is to have the same "pattern-ed" syntax as with `Maybe.withDefault`. It's not important **but it's handy** (currying, point-free style). It's the kind of function that you'll see re-write on every project because it's not standard. 

Indeed, `ifElse` looks more Elm-ish to me and it would great simplify this MR by avoiding the second commit :+1:

**Comment by cs** [comment]
After our discussion, I have defined and tested the following function in my own codebase and it works nicely ;)

```
ifElse : a -> a -> Bool -> a
ifElse ifTrue ifFalse predicate =
    if predicate then
        ifTrue

    else
        ifFalse
```

@Chadtech What do you think? Your package, your call.

**Comment by Chadtech** [comment]
Lets do it! If you change this PR to `ifElse` I'll merge it and publish it.

Thanks

**Comment by cs** [comment]
@Chadtech I don't know how to "change" this PR, because it's not mine ;) Created a new one instead.

**Comment by etiennebatise** [comment]
Nice! :smile: 

Closing because of #6

**Pull request closed without merging**
